service: desafio-bgc

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'sa-east-1'}
  memorySize: 128
  timeout: 3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:sa-east-1:${env:ACCOUNT_ID}:table/Products
  environment:
    TABLE_NAME: Products
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    ACCESS_KEY: ${env:ACCESS_KEY}
    SECRET_KEY: ${env:SECRET_KEY}

functions:
  getProducts:
    handler: src/api/getProducts.handler
    events:
      - http:
          path: products
          method: get
